module.exports = {
  URWA_ENV_VAR: "URWA_ENV",
  MONGO_DB_ENV_USERNAME_VAR: "MONGO_DB_USERNAME",
  MONGO_DB_ENV_PASSWORD_VAR: "MONGO_DB_PASSWORD",
  AT_ENV_SECRET_VAR: "AT_SECRET",
  RT_ENV_SECRET_VAR: "RT_SECRET",
};
